### ISSUE TITLE
PC VESC Tool stuck in dark mode

### ISSUE THREAD

**Issue by surfdado** [vedderb/vesc_tool#136]
How do I change it to normal mode?

**Comment by vedderb** [comment]
There is only a dark mode from now on to make it more consistent with the mobile version as parts of it are being integrated in the desktop version. @Jfriesen222 put in a few days of effort to make it, and I really like the way it turned out so far:
https://github.com/vedderb/vesc_tool/pull/133

At the moment there is no plan to support both a light and dark mode as it is easy to miss something and end up with unreadable text.

If you see any place with unreadable text or bad contrast please let me know and I will get it fixed.

**Comment by vedderb** [comment]
Fixes with this:
https://github.com/vedderb/vesc_tool/pull/148

**Comment by kubark42** [comment]
@vedderb thanks so much for the fix! See https://github.com/vedderb/vesc_tool/issues/165 for an explanation of why this was so important to me.
