### ISSUE TITLE
C++11 Flags

### ISSUE THREAD

**Issue by fabolhak** [vedderb/vesc_tool#7]
Hello, 
thank you for the great tool. It is pretty cool :). However I have problems building it on my Ubuntu 16.04. machine because is is not compiling with C++11 by default (a lot of warnings coming up). Is there any compiler flag I have to configure? :)

**Comment by fabolhak** [comment]
I got it compiling correctly by adding `CONFIG += c++11` to the vesc_tool.pro file :)

**Comment by rewolff** [comment]
It compiles without any additions. However, the warning: 
./```
vescinterface.h:132:27: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
     bool mSendCanBefore = false;
```
indicates to me that it is ignoring the intializer! As, in this case, it is likely that the "false" turns into zero anyway, chances are that it will still work. But with hundreds of these warnings, it is entirely possible that a non-zero initializer is required somewhere.... 

In fact, the compiled binary locks up quite quickly in my case, Not sure what the cause is, but I'm going to try adding the C++11....
